# Regexes with \. should be \\. inside the TOML parser

[URL_COMPLEX]
regex = "http:/google\\.github\\.io/[a-z]{10}/version[0-9]{3}/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextUrlComplex", "OffXorUrlComplex", "GptUrlComplex", "GperfUrlComplex", "NaiveUrlComplex" , "AesUrlComplex"]

[URL_FIXED_PATTERN]
regex = "http:/google\\.github\\.io/farmhash/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextUrl", "OffXorUrl", "NaiveUrl", "GptUrl", "GperfUrl", "AesUrl"]

[MAC]
regex = "([0-9a-fA-F]{2}-){5}[0-9a-fA-F]{2}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextMac", "OffXorMac", "NaiveMac", "GptMac", "GperfMac", "AesMac"]

[CPF]
regex = "(([0-9]{3})\\.){2}[0-9]{3}-[0-9]{2}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextCPF", "OffXorCPF", "NaiveCPF", "GptCPF", "GperfCPF", "AesCPF"]

[SSN]
regex = "[0-9]{3}-[0-9]{2}-[0-9]{4}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextSSN", "OffXorSSN", "NaiveSSN", "GptSSN", "GperfSSN", "AesSSN"]

[IPV4]
regex = "(([0-9]{3})\\.){3}[0-9]{3}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextIPV4", "OffXorIPV4", "NaiveIPV4", "GptIPV4", "GperfIPV4", "AesIPV4"]

[IPV6]
regex = "([0-9a-fA-F]{4}:){7}[0-9a-fA-F]{4}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextIPV6", "OffXorIPV6", "NaiveIPV6", "GptIPV6", "GperfIPV6", "AesIPV6"]

[INTS]
regex = "[0-9]{100}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextINTS", "OffXorINTS", "NaiveINTS", "GptINTS", "GperfINTS", "AesINTS"]

[INT4]
regex = "[0-9]{4}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextINT4", "OffXorINT4", "NaiveINT4", "AesINTS"]
