/**
 * @file gperf-hashes.h
 * @brief This file contains a collection of hash functions generated by gperf using 1000 keys generated by keygen using the default seed.
 */

#ifndef GPERF_HASHES_HPP
#define GPERF_HASHES_HPP

#include <stdlib.h>

/**
 * @brief Calculates the hash of a URL complex string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfUrlComplexHash (const char *str, size_t len);

/**
 * @brief Calculates the hash of a URL string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfUrlHash (const char *str, size_t len);

/**
 * @brief Calculates the hash of a MAC address string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfMACHash (const char *str, size_t len);

/**
 * @brief Calculates the hash of a CPF number string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfCPFHash (const char *str, size_t len);

/**
 * @brief Calculates the hash of a SSN number string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfSSNHash (const char *str, size_t len);

/**
 * @brief Calculates the hash of an IPV4 address string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfIPV4Hash (const char *str, size_t len);

/**
 * @brief Calculates the hash of an IPV6 address string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfIPV6Hash (const char *str, size_t len);

/**
 * @brief Calculates the hash of an INTS string.
 * 
 * @param str The string to hash.
 * @param len The length of the string.
 * @return The hash of the string.
 */
unsigned int
GperfINTSHash (const char *str, size_t len);

#endif